#!/usr/bin/perl

use File::Basename;

#
# Generates a "statistics.tbl" table from a directory containing TRAP-AT conformers generated by mk_chains
# Statistics table format:
# pdb_name	mw	Rg	T-T min	T-T avg	T-Tmax	A-A min, etc.
#

$rg_bin = '/export/foster_group/ihms_scratch/tools/rg_calc'; #'/Volumes/FosterLab/users/ihms/Projects/TRAP_AT/models/chain_structure/pdb_score/bin/rg_calc';

$a1_bin = '/export/foster_group/ihms_scratch/tools/atom_distance'; #'/Volumes/FosterLab/users/ihms/Projects/TRAP_AT/models/chain_structure/pdb_score/bin/atom_distance';

$a2_bin = '/export/foster_group/ihms_scratch/tools/2atom_distance'; #'/Volumes/FosterLab/users/ihms/Projects/TRAP_AT/models/chain_structure/pdb_score/bin/2atom_distance';

# do we skip conformers that have a T-T or A-A minimum distance of $clash_cutoff?
$clash_skip = 0;
$clash_cutoff = 0.01;

if( $#ARGV == -1 )
{
	print "Usage: make_pdb_statistics.pl <pdb_dir>\n";
	exit;
}

# test binary locations
if( ! -X $rg_bin )
{
	print "rg_calc binary not executable\n";
	exit;
}
if( ! -X $a1_bin )
{
	print "atom_distance binary not executable\n";
	exit;
}
if( ! -X $a2_bin )
{
	print "2atom_distance binary not executable\n";
	exit;
}

@files = glob( $ARGV[0]."/*.pdb" );
if($#files < 0)
{
	print "No .pdb files found in provided directory.";
	exit;
}

for $file (@files)
{
	($name,$path,$suffix) = fileparse($file);
	
	# get PDB mw from header
	$s = `head -n 50 $file`;
	$s =~ m/MW\:(\d+?.\d?)\s+/;
	$mw = $1;
	
	# get PDB Rg
	$s = `$rg_bin $file`;
	@a = split("\t",$s);
	chomp(@a);
	$rg = @a[1];
	
	# get PDB TRAP-TRAP distances
	$s = `$a1_bin QT $file`;
	@T_T = split("\t",$s);
	chomp(@T_T);
	
	if( ($clash_skip > 0) && ($T_T[2] < $clash_cutoff) ){
		next;
	}
	
	# get PDB AT-AT distances
	$s = `$a1_bin QA $file`;
	@A_A = split("\t",$s);
	chomp(@A_A);
	
	if( ($clash_skip > 0) && ($A_A[2] < $clash_cutoff) ){
		next;
	}
	
	# get PDB TRAP-AT distances
	$s = `$a2_bin QT QA $file`;
	@T_A = split("\t",$s);
	chomp(@T_A);
	
	print "$name\t$mw\t$rg\t$T_T[2]\t$T_T[3]\t$T_T[4]\t$A_A[2]\t$A_A[3]\t$A_A[4]\t$T_A[3]\t$T_A[4]\t$T_A[5]\n";
}